import asyncio
import json
from pathlib import Path
from types import SimpleNamespace

from app.agents.judge.agent import evaluate_and_score_node
from app.agents.judge.prompt import get_judge_evaluation_prompt
from app.agents.performance.agent import performance_agent_node
from app.agents.performance.prompt import get_performance_prompt
from app.agents.security.agent import security_agent_node
from app.agents.security.prompt import get_security_prompt
from app.agents.sre.agent import sre_agent_node
from app.agents.sre.prompt import get_sre_prompt
from app.config import settings
from app.harness.tools import recent_tool_executions
from app.types import DebateRoundEnvelope


def format_tool_executions_md() -> str:
    if not recent_tool_executions:
        return "### Active Tool & Skill Access (Executed During Turn)\n*(No external tools were invoked during this turn)*\n\n"
    res = ["### Active Tool & Skill Access (Executed During Turn)\n"]
    for ex in recent_tool_executions:
        res.append(f"- **`{ex['tool_name']}`** `args={ex['args']}` -> `{ex['result_preview']}`")
    res.append("\n")
    return "\n".join(res)


class MockState(dict):
    def to_dict(self):
        return dict(self)

async def generate_raw_inspection_file():
    settings.mock_mode = False
    project_id = "live_sim_proj_002"

    from app.utils import FilesystemJail
    scratchpad_file = FilesystemJail.BASE_OUTPUT_DIR / "state" / f"{project_id}_scratchpad.json"
    if scratchpad_file.exists():
        scratchpad_file.unlink()

    state = MockState({
        "project_id": project_id,
        "concept": "High-Throughput Global Financial Transactions API",
        "current_round": 1,
        "rounds_history": [],
    })
    ctx = SimpleNamespace(state=state)

    lines = []
    lines.append("# Complete Raw LLM Prompts & Outputs Inspection Log\n")
    lines.append("This document records the exact, un-truncated prompt string received by each agent LLM after its prompt function executed, along with the exact raw structured output generated by each agent.\n")
    lines.append("---")

    # =========================================================================
    # ROUND 1
    # =========================================================================
    lines.append("\n# ROUND 1: INITIAL DEBATE\n")

    # 1. Performance Architect
    raw_perf_prompt_r1 = get_performance_prompt(
        concept=ctx.state["concept"],
        current_round=1,
        history=ctx.state.get("rounds_history", []),
        project_id=ctx.state.get("project_id"),
    )
    recent_tool_executions.clear()
    perf_events_r1 = [e async for e in performance_agent_node._func(ctx, {})]
    perf_out_r1 = perf_events_r1[-1].output

    lines.append("## 1. Performance Lead Architect (Round 1)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_performance_prompt`)\n")
    lines.append("```markdown\n" + raw_perf_prompt_r1.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(perf_out_r1, indent=2) + "\n```\n")
    lines.append("---")

    # 2. Security Auditor
    proposal_str_r1 = perf_out_r1.get("proposal", "") if isinstance(perf_out_r1, dict) else getattr(perf_out_r1, "proposal", "")
    raw_sec_prompt_r1 = get_security_prompt(
        proposal=proposal_str_r1,
        project_id=ctx.state.get("project_id"),
        agreement_summary=None,
        previous_threats=[],
    )
    recent_tool_executions.clear()
    sec_events_r1 = [e async for e in security_agent_node._func(ctx, perf_out_r1)]
    sec_out_r1 = sec_events_r1[-1].output

    lines.append("## 2. Security Auditor (Round 1)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_security_prompt`)\n")
    lines.append("```markdown\n" + raw_sec_prompt_r1.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(sec_out_r1, indent=2, default=str) + "\n```\n")
    lines.append("---")

    # 3. SRE Auditor
    raw_sre_prompt_r1 = get_sre_prompt(
        proposal=proposal_str_r1,
        project_id=ctx.state.get("project_id"),
        agreement_summary=None,
        previous_gaps=[],
    )
    recent_tool_executions.clear()
    sre_events_r1 = [e async for e in sre_agent_node._func(ctx, perf_out_r1)]
    sre_out_r1 = sre_events_r1[-1].output

    lines.append("## 3. Site Reliability Engineer (SRE Auditor) (Round 1)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_sre_prompt`)\n")
    lines.append("```markdown\n" + raw_sre_prompt_r1.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(sre_out_r1, indent=2, default=str) + "\n```\n")
    lines.append("---")

    # 4. Master Architect Judge
    sec_critique_r1 = (sec_out_r1.get("security_rubric", {}) if isinstance(sec_out_r1, dict) else {}).get("detailed_critique") or (sec_out_r1["security_critique"] if isinstance(sec_out_r1, dict) else getattr(sec_out_r1, "security_critique", ""))
    sre_critique_r1 = (sre_out_r1.get("sre_rubric", {}) if isinstance(sre_out_r1, dict) else {}).get("detailed_critique") or (sre_out_r1["sre_critique"] if isinstance(sre_out_r1, dict) else getattr(sre_out_r1, "sre_critique", ""))
    combined_critiques_r1 = f"### Security Critique\n{sec_critique_r1}\n\n### SRE Critique\n{sre_critique_r1}"

    sec_rubric_r1 = sec_out_r1.get("security_rubric") if isinstance(sec_out_r1, dict) else getattr(sec_out_r1, "security_rubric", None)
    sre_rubric_r1 = sre_out_r1.get("sre_rubric") if isinstance(sre_out_r1, dict) else getattr(sre_out_r1, "sre_rubric", None)
    open_blockers_r1 = []
    if sec_rubric_r1:
        reg = sec_rubric_r1.get("stride_threat_register", []) if isinstance(sec_rubric_r1, dict) else getattr(sec_rubric_r1, "stride_threat_register", [])
        for t in reg:
            open_blockers_r1.append(t)
    if sre_rubric_r1:
        reg = sre_rubric_r1.get("sre_gap_register", []) if isinstance(sre_rubric_r1, dict) else getattr(sre_rubric_r1, "sre_gap_register", [])
        for g in reg:
            open_blockers_r1.append(g)

    raw_judge_prompt_r1 = get_judge_evaluation_prompt(
        proposal=proposal_str_r1,
        combined_critiques=combined_critiques_r1,
        rounds_history=[],
        open_blockers=open_blockers_r1,
    )
    judge_input_r1 = {
        "security_agent_node": sec_out_r1,
        "sre_agent_node": sre_out_r1,
    }
    recent_tool_executions.clear()
    judge_events_r1 = [e async for e in evaluate_and_score_node._func(ctx, judge_input_r1)]
    r1_scores = ctx.state["rounds_history"][-1]

    lines.append("## 4. Master Architect Judge (Round 1)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_judge_evaluation_prompt`)\n")
    lines.append("```markdown\n" + raw_judge_prompt_r1.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(r1_scores, indent=2, default=str) + "\n```\n")
    lines.append("---")

    # =========================================================================
    # ROUND 2
    # =========================================================================
    ctx.state["current_round"] = 2
    lines.append("\n# ROUND 2: DELTA REFINEMENT & MITIGATION\n")

    # 1. Performance Architect R2
    raw_perf_prompt_r2 = get_performance_prompt(
        concept=ctx.state["concept"],
        current_round=2,
        history=ctx.state.get("rounds_history", []),
        project_id=ctx.state.get("project_id"),
    )
    recent_tool_executions.clear()
    perf_events_r2 = [e async for e in performance_agent_node._func(ctx, {})]
    perf_out_r2 = perf_events_r2[-1].output

    lines.append("## 1. Performance Lead Architect (Round 2)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_performance_prompt`)\n")
    lines.append("```markdown\n" + raw_perf_prompt_r2.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(perf_out_r2, indent=2) + "\n```\n")
    lines.append("---")

    # 2. Security Auditor R2
    proposal_str_r2 = perf_out_r2.get("proposal", "") if isinstance(perf_out_r2, dict) else getattr(perf_out_r2, "proposal", "")
    raw_sec_prompt_r2 = get_security_prompt(
        proposal=proposal_str_r2,
        project_id=ctx.state.get("project_id"),
        agreement_summary=ctx.state.get("latest_agreement_summary"),
        previous_threats=open_blockers_r1,
    )
    recent_tool_executions.clear()
    sec_events_r2 = [e async for e in security_agent_node._func(ctx, perf_out_r2)]
    sec_out_r2 = sec_events_r2[-1].output

    lines.append("## 2. Security Auditor (Round 2)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_security_prompt` with STRIDE Ledger Injection)\n")
    lines.append("```markdown\n" + raw_sec_prompt_r2.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(sec_out_r2, indent=2, default=str) + "\n```\n")
    lines.append("---")

    # 3. SRE Auditor R2
    raw_sre_prompt_r2 = get_sre_prompt(
        proposal=proposal_str_r2,
        project_id=ctx.state.get("project_id"),
        agreement_summary=ctx.state.get("latest_agreement_summary"),
        previous_gaps=[],
    )
    recent_tool_executions.clear()
    sre_events_r2 = [e async for e in sre_agent_node._func(ctx, perf_out_r2)]
    sre_out_r2 = sre_events_r2[-1].output

    lines.append("## 3. Site Reliability Engineer (SRE Auditor) (Round 2)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_sre_prompt` with Ledger Injection)\n")
    lines.append("```markdown\n" + raw_sre_prompt_r2.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(sre_out_r2, indent=2, default=str) + "\n```\n")
    lines.append("---")

    # 4. Master Architect Judge R2
    sec_critique_r2 = (sec_out_r2.get("security_rubric", {}) if isinstance(sec_out_r2, dict) else {}).get("detailed_critique") or (sec_out_r2["security_critique"] if isinstance(sec_out_r2, dict) else getattr(sec_out_r2, "security_critique", ""))
    sre_critique_r2 = (sre_out_r2.get("sre_rubric", {}) if isinstance(sre_out_r2, dict) else {}).get("detailed_critique") or (sre_out_r2["sre_critique"] if isinstance(sre_out_r2, dict) else getattr(sre_out_r2, "sre_critique", ""))
    combined_critiques_r2 = f"### Security Critique\n{sec_critique_r2}\n\n### SRE Critique\n{sre_critique_r2}"

    raw_judge_prompt_r2 = get_judge_evaluation_prompt(
        proposal=proposal_str_r2,
        combined_critiques=combined_critiques_r2,
        rounds_history=ctx.state.get("rounds_history", []),
        open_blockers=open_blockers_r1,
    )
    judge_input_r2 = {
        "security_agent_node": sec_out_r2,
        "sre_agent_node": sre_out_r2,
    }
    recent_tool_executions.clear()
    judge_events_r2 = [e async for e in evaluate_and_score_node._func(ctx, judge_input_r2)]
    r2_scores = ctx.state["rounds_history"][-1]

    lines.append("## 4. Master Architect Judge (Round 2)\n")
    lines.append("### Raw Input Prompt Received by LLM (`get_judge_evaluation_prompt` with Delta Evaluation Card)\n")
    lines.append("```markdown\n" + raw_judge_prompt_r2.strip() + "\n```\n")
    lines.append(format_tool_executions_md())
    lines.append("### Raw Output Generated by Agent\n")
    lines.append("```json\n" + json.dumps(r2_scores, indent=2, default=str) + "\n```\n")

    artifact_dir = Path("C:/Users/Fred/.gemini/antigravity-ide/brain/f785e370-4e1e-4774-a0b8-40262bae09ea")
    artifact_dir.mkdir(parents=True, exist_ok=True)
    target_file = artifact_dir / "raw_llm_prompts_and_outputs.md"
    target_file.write_text("\n".join(lines), encoding="utf-8")

    local_copy = Path("raw_llm_prompts_and_outputs.md")
    local_copy.write_text("\n".join(lines), encoding="utf-8")

    print(f"Successfully saved complete raw prompts and outputs to: {target_file}")
    print(f"Also saved local copy to: {local_copy.resolve()}")

if __name__ == "__main__":
    asyncio.run(generate_raw_inspection_file())
